apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jitsi-jicofo
  name: jitsi-jicofo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-jicofo
  template:
    metadata:
      labels:
        app: jitsi-jicofo
    spec:
      containers:
      - name: jicofo
        image: kcdominion/lefebvre-jitsi-jicofo:v2
        imagePullPolicy: Always
        env:
        - name: AUTH_TYPE
          value: internal
        - name: ENABLE_AUTH
          value: "1"
        - name: JIBRI_BREWERY_MUC
          value: jibribrewery
        - name: JIBRI_PENDING_TIMEOUT
          value: "90"
        - name: JICOFO_AUTH_PASSWORD
          value: c8fb61b52d9b3aa8c6671568ac4e5696
        - name: JICOFO_AUTH_USER
          value: focus
        - name: JICOFO_COMPONENT_SECRET
          value: c6655cf2ab6ad22d8f38b14b45845a6d
        - name: JIGASI_BREWERY_MUC
          value: jigasibrewery
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: TZ
          value: America/Guatemala
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_SERVER
          value: 10.102.128.203