apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jitsi-jvb
  name: jitsi-jvb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-jvb
  template:
    metadata:
      labels:
        app: jitsi-jvb
    spec:
      containers:
      - name: jitsi-jvb
        image: kcdominion/lefebvre-jitsi-jvb:v2
        imagePullPolicy: Always
        env:
        - name: XMPP_SERVER
          value: 10.102.128.203 
        - name: DOCKER_HOST_ADDRESS
          value: 192.168.99.104
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: JVB_STUN_SERVERS
          value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
        - name: JICOFO_AUTH_USER
          value: focus
        - name: JVB_TCP_HARVESTER_DISABLED
          value: "true"
        - name: JVB_AUTH_USER
          value: jvb
        - name: JVB_PORT
          value: "10000"
        - name: JVB_TCP_PORT
          value: "4443"
        - name: JVB_AUTH_PASSWORD
          value: 328bd050f2ce49a49fbd63f316b15d15
        - name: JICOFO_AUTH_PASSWORD
          value: c8fb61b52d9b3aa8c6671568ac4e5696
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: TZ
          value: America/Guatemala
        ports:
        - containerPort: 10000
          protocol: UDP
        - containerPort: 4443
