apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi-jvb
  name: jvb-service
spec:
  ports:
  - name: "10000"
    port: 10000
    protocol: UDP
    targetPort: 10000
  - name: "4443"
    port: 4443
    targetPort: 4443
  selector:
    app: jitsi-jvb
