apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jitsi-prosody
  name: jitsi-prosody-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jitsi-prosody
  template:
    metadata:
      labels:
        app: jitsi-prosody
    spec:
      containers:
      - name: jitsi-prosody
        image: kcdominion/lefebvre-jitsi-prosody:v2
        imagePullPolicy: Always
        env:
        - name: AUTH_TYPE
          value: internal
        - name: ENABLE_AUTH
          value: "1"
        - name: ENABLE_GUESTS
          value: "1"
        - name: JIBRI_RECORDER_PASSWORD
          value: ead7e81257962ab262066b26dcd40cf7
        - name: JIBRI_RECORDER_USER
          value: recorder
        - name: JIBRI_XMPP_PASSWORD
          value: 095915bd19a7a505ca39dc4815a6f7d4
        - name: JIBRI_XMPP_USER
          value: jibri
        - name: JICOFO_AUTH_PASSWORD
          value: c8fb61b52d9b3aa8c6671568ac4e5696
        - name: JICOFO_AUTH_USER
          value: focus
        - name: JICOFO_COMPONENT_SECRET
          value: c6655cf2ab6ad22d8f38b14b45845a6d
        - name: JIGASI_XMPP_PASSWORD
          value: d22298aaf74e58e2dbdceeaa8dfc4056
        - name: JIGASI_XMPP_USER
          value: jigasi
        - name: JVB_AUTH_PASSWORD
          value: 328bd050f2ce49a49fbd63f316b15d15
        - name: JVB_AUTH_USER
          value: jvb
        - name: TZ
          value: America/Guatemala
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_GUEST_DOMAIN
          value: guest.meet.jitsi
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: XMPP_RECORDER_DOMAIN
          value: recorder.meet.jitsi
        ports:
        - containerPort: 5222
        - containerPort: 5347
        - containerPort: 5280

